spring.application.name=reactserver
server.port=8080

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/mihelper_db
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate (optional)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


jwt.secret=zG5tWq9T+9v8qFJ2nX1Hc8aK5t2bL7mQyP0v6N1gR8s=

